frase = str(input('Digite uma frase: ')).strip().upper()
fr = frase.split()
print('A letra A aparece {} vezes'.format(frase.upper().count('A')))
print('A primeira letra A apareceu na posição {}'.format(frase.upper().find('A')+1))
print('A última letra A apareceu na posição {}'.format(frase.upper().rfind('A')+1))
